//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BikeStores2Entities : DbContext
    {
        public BikeStores2Entities()
            : base("name=BikeStores2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<vwDocumentLookup> vwDocumentLookups { get; set; }
        public virtual DbSet<InvoiceDocument> InvoiceDocuments { get; set; }
    
        public virtual int spAddFile(string invoice_PO, string invoice_MIME, byte[] invoice_document, Nullable<int> order_id)
        {
            var invoice_POParameter = invoice_PO != null ?
                new ObjectParameter("invoice_PO", invoice_PO) :
                new ObjectParameter("invoice_PO", typeof(string));
    
            var invoice_MIMEParameter = invoice_MIME != null ?
                new ObjectParameter("invoice_MIME", invoice_MIME) :
                new ObjectParameter("invoice_MIME", typeof(string));
    
            var invoice_documentParameter = invoice_document != null ?
                new ObjectParameter("invoice_document", invoice_document) :
                new ObjectParameter("invoice_document", typeof(byte[]));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddFile", invoice_POParameter, invoice_MIMEParameter, invoice_documentParameter, order_idParameter);
        }
    
        public virtual ObjectResult<spGetetAllFiles_Result> spGetetAllFiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetetAllFiles_Result>("spGetetAllFiles");
        }
    
        public virtual ObjectResult<spGetFileDetails_Result> spGetFileDetails(Nullable<int> invoice_id)
        {
            var invoice_idParameter = invoice_id.HasValue ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFileDetails_Result>("spGetFileDetails", invoice_idParameter);
        }
    }
}
